#INTRODUCTION TO DIGITAL SOIL MAPPING
#EXERCISE 3.4 Feature Space Coverage Samping and 
#CONDITIONED LATIN HYPERCUBE SAMPLING
#########################################################################################################################
# This exercise compares FSCS and cLHS sampling design using covariates 
# these will be compared to the distribution of the covariates

## load libraries
packs = c('terra', 'sgsR', 'sf', 'ggplot2', 'ggpubr',
          'grid',
          'rstac',
          'hexbin',
          "geometry", # for convhulln
          "spatstat") # for nndist)
for (p in packs){
  if(!requireNamespace(p, quietly = TRUE)){
    install.packages(p, quiet = TRUE)
    require(p)
  }
  library(p,character.only = TRUE)
}


# 1. Load volcano dataset
data("volcano")

# Load your existing DEM to get its extent
# Assuming 'r_geo' is your georeferenced volcano raster from before
# 2. Convert to SpatRaster
# We transpose 't()' to fix the matrix-to-raster orientation
v_rast <- rast(t(volcano))

# 3. Assign the Projection (CRS)
crs(v_rast) <- "EPSG:2193"

# 4. Assign the Extent
# The classic volcano is an 87x61 grid with 10m spacing. 
# To align it with volcano2, use the exact extent from that dataset:
ext(v_rast) <- c(1757390, 1758000, 5917560, 5918430)

# 5. Flip if needed
# Depending on your R version/setup, you may need to flip to match North
dem <- flip(v_rast, direction="vertical")
slope  <- terrain(dem, "slope", unit="degrees")
aspect <- terrain(dem, "aspect", unit="degrees")

image(dem, col = terrain.colors(100), asp = 87/61)

# Load your existing DEM to get its extent
# Assuming 'r_geo' is your georeferenced volcano raster from before
dem_ext <- ext(dem)
dem_crs <- crs(dem)

# 1. Project your georeferenced volcano raster extent to Longitude/Latitude
# Assuming 'v_rast' is your georeferenced volcano SpatRaster
bbox_longlat <- dem |> 
  project("EPSG:4326") |> 
  ext() |> 
  as.vector()
# 1. Get the extent in Long/Lat
v_ext <- dem |> project("EPSG:4326") |> ext()

# 2. Manually construct the bbox to ensure correct [W, S, E, N] order
# New Zealand Longitudes are ~174, Latitudes are ~-36
bbox_fix <- c(v_ext$xmin, v_ext$ymin, v_ext$xmax, v_ext$ymax)

# 3. search collection form scenes
it_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "landsat-c2-l2",
              bbox = bbox_fix, 
              datetime = "2023-01-01T00:00:00Z/2023-12-31T23:59:59Z",
              limit = 10) |>
  get_request()

# 4. Sign the items
it_signed <- items_sign(it_obj, sign_planetary_computer())


# 3. Filter for low cloud cover from the signed results
it_filtered <- it_signed |> 
  items_filter(properties$`eo:cloud_cover` < 80)

# 4. Extract URLs for Red (B4) and NIR (B5)
# Using the first item in the filtered list
item <- it_filtered$features[[1]]

# Get the URLs for the Red and NIR bands
red_url <- item$assets$red$href
nir_url <- item$assets$nir$href

# Read directly from AWS into terra (as COGs)
ls_red <- rast(red_url)
ls_nir <- rast(nir_url)

# Project and crop to your DEM extent
ls_red_cropped <- crop(project(ls_red, dem_crs), dem)
ls_nir_cropped <- crop(project(ls_nir, dem_crs), dem)

# Now calculate NDVI
ndvi <- (ls_nir_cropped - ls_red_cropped) / (ls_nir_cropped + ls_red_cropped)

#combine similar rasters
spec <- c(ls_red_cropped, ls_nir_cropped, ndvi)
elev <- c(dem, aspect, slope)

# We resample the spectral data to match 'dem' exactly
spec_aligned <- resample(spec, dem, method = "bilinear")

# 2. Combine into one stac
cov_stack <- c(spec_aligned, elev)

plot(cov_stack)

# scale all continuous data in the raster stack
cov_stack = scale(cov_stack)

# assign names to covariates in stack for simplification and clarification
names(cov_stack) = c(
  'red', 'nir', 'ndvi', 'dem', 
  'aspect', 'slope'
)

# view the covariate stack
plot(cov_stack)


# set seed for reproducability
set.seed (151)


# Generate cLHS sample points

## The number of points generated by changing thh nSamp parameter
clhs_pts <- sample_clhs(cov_stack, nSamp=150, iter = 1000, plot = T)

##

# Generate FSCS - centroid sample points

## Create sample points at cluster centers
cent_pts = sample_nc(
  cov_stack, nSamp = 15, k=10, iter=1000, plot=T
)


# Generate FSCS - stratified sample points

# first use kmeans to create clusters in feature space
k_strat = strat_kmeans(
  cov_stack, 15, iter=1000, plot=TRUE, details=TRUE
)

# Create a equal number of points in each cluster
fscs_pts = sample_strat(k_strat$raster, 10, 'equal', plot=TRUE, method='random')

# plot the clusters
plot(k_strat$raster)
points(fscs_pts)
points(cent_pts, "red")

# Extract data and view results of the various sampling techniques


# extract covariate data and append for data comparisons below
fscs_covs = terra::extract(cov_stack, fscs_pts)
fscs_pts = cbind(fscs_pts, fscs_covs)

# Summary really doesn't give us a good perspective
summary(clhs_pts)



## Generate plots to compare the covariate distribution to our sample datasets

## First we need setup a data frame that represents the Original data. 
## To do this we need to convert the raster stack to a data frame. 

## We could convert the raster stack where every pixel but would be cumbersome,
## so we will draw a large regular sample of a million points
large_sample <- na.omit(
  spatSample(x=cov_stack, size = 1000000, method = "regular", as.df = T
  ))

## Combine the large sample, 
##  which is a representative the covariate stack
## and the cLHS sampled data.

## rbind will vertically stack the dataframes and allows us to add new column
## "method" that denotes the source. We also excluding the geometry

s <- rbind(
  data.frame(method = "Large Sample", large_sample),
  data.frame(method = "cLHS", subset(st_drop_geometry(clhs_pts), select = -type)),
  data.frame(method = "FSCS rand", subset(st_drop_geometry(fscs_pts), select = -c(type, strata, ID))),
  data.frame(method = "FSCS cent", subset(st_drop_geometry(cent_pts), select = -kcenter))
)


## Generate box plots and kernal density plots to compare the distribution 
## between cLHS samples and the covariate data.

## Box plots of cLHS sample vs large systematic sample representing population of each raster

ggplot(s, aes(x = method, y = ndvi, color = method)) + 
  geom_boxplot(cex = 1) + 
  labs(title = "NDVI")
## Create two more box plots for two other covariates
ggplot(s, aes(x = method, y = dem, color = method)) + 
  geom_boxplot(cex = 1) + 
  labs(title = "DEM")

## Kernal density plots of cLHS sample vs large systematic sample representing population of each raster
ggplot(s, aes(x = ndvi, col = method)) + 
  geom_density(cex = 2) + 
  labs(title = "NDVI")
## Create two more density plots for two other covariates
ggplot(s, aes(x = dem, col = method)) + 
  geom_density(cex = 2) + 
  labs(title = "DEM")

## Feature Space plots

# the large covariate sample is a bit too large for these next few plots
med_sample <- na.omit(
  spatSample(x=cov_stack, size = 50000, method = "regular", as.df = T
  ))

centroids = k_strat$details$centers
p1 = ggplot(med_sample, aes(x=ndvi, y=dem)) + geom_point(alpha=0.2, size=0.7) +
  geom_point(data=fscs_pts, color="cyan", size=1.5, shape=17) + 
  labs(title = "Kmean Stratification")
p2 = ggplot(med_sample, aes(x=ndvi, y=dem)) + geom_point(alpha=0.2, size=0.7) +
  geom_point(data=clhs_pts, color='green', size=1.5, shape=16) + 
  labs(title = "CLHS")

p3 = ggplot(med_sample, aes(x=ndvi, y=dem)) + geom_point(alpha=0.2, size=0.7) +
  geom_point(data=cent_pts, color='hotpink', size=2, shape=18) + 
  labs(title = "Kmean Centroids")

# Build one more feature space plot
ggarrange(p3, p2, p1, common.legend = T, legend = "right", ncol = 3)

# build princomp for cti and iron
#Run PCA using prcomp (more accurate but slower for large data)
# Use 'scale = TRUE' to standardize variables with different units
names(cov_stack)
pca_model <- prcomp(cov_stack[[-7]], scale = TRUE)

# 3. Create a SpatRaster of the Principal Components
pca_raster <- predict(cov_stack[[-7]], pca_model)

plot(pca_raster[[1]])


#### NEW SECTION
### PLOTS
# 1. Prepare color palette
reds = colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd")[-1])

# 2. Convert raster for background
df_raster <- as.data.frame(pca_raster[[1:2]], xy=FALSE)

# 3. Create Plots - Note the "ov.rnd[,-1]" to remove the ID column
# Plot 1: cLHS
ov.rnd <- terra::extract(pca_raster[[1:2]], clhs_pts)
clhs.p <- ggplot(df_raster, aes(x=PC1, y=PC2)) +
  geom_hex(bins = 50) +
  scale_fill_gradientn(colors = reds(80), trans = "log10") +
  geom_point(data = as.data.frame(ov.rnd[,-1]), aes(x=PC1, y=PC2), shape="+", size=4, color="black") +
  theme_minimal() + labs(title="cLHS")

# Plot 2: FSCS Stratified
ov.rnd <- terra::extract(pca_raster[[1:2]], fscs_pts)
fscs.s.p <- ggplot(df_raster, aes(x=PC1, y=PC2)) +
  geom_hex(bins = 50) +
  scale_fill_gradientn(colors = reds(80), trans = "log10") +
  geom_point(data = as.data.frame(ov.rnd[,-1]), aes(x=PC1, y=PC2), shape="+", size=4, color="black") +
  theme_minimal() + labs(title="FSCS - Stratified")

# Plot 3: FSCS Centroid
ov.rnd <- terra::extract(pca_raster[[1:2]], cent_pts)
fscs.c.p <- ggplot(df_raster, aes(x=PC1, y=PC2)) +
  geom_hex(bins = 50) +
  scale_fill_gradientn(colors = reds(80), trans = "log10") +
  geom_point(data = as.data.frame(ov.rnd[,-1]), aes(x=PC1, y=PC2), shape="+", size=4, color="black") +
  theme_minimal() + labs(title="FSCS - Centroid")

# 4. Arrange and Display
combined_plot <- ggarrange(clhs.p, fscs.c.p, fscs.s.p, 
                           common.legend = TRUE, 
                           legend = "right", 
                           ncol = 3)

# Use annotate_figure to add the main title to ggarrange
print(annotate_figure(combined_plot, top = text_grob("Comparison of Sampling Strategies in Feature Space", size = 14)))

# descriptive stats
# 1. Prepare Population (True Feature Space) stats
pop_means <- colMeans(df_raster)
pop_sds <- apply(df_raster, 2, sd)

# 2. Extract PCA coordinates for each sample (removing the ID column)
sample_list <- list(
  "cLHS" = terra::extract(pca_raster[[1:2]], clhs_pts)[,-1],
  "FSCS - Stratified" = terra::extract(pca_raster[[1:2]], fscs_pts)[,-1],
  "FSCS - Centroid" = terra::extract(pca_raster[[1:2]], cent_pts)[,-1]
)

# 3. Create a function to calculate all 4 comparison metrics
calc_all_metrics <- function(pts_df, pop_means, pop_sds) {
  # A. Convex Hull Area (Extent of Coverage)
  area <- convhulln(pts_df, options = "FA")$vol
  
  # B. Mean Nearest Neighbor Distance (Spread/Uniformity)
  avg_dist <- mean(nndist(pts_df[,1], pts_df[,2]))
  
  # C. Representativeness Score (Euclidean distance between Sample Mean and Pop Mean)
  # Lower is better (0 = perfect representation of the center)
  sample_means <- colMeans(pts_df)
  rep_score <- sqrt(sum((sample_means - pop_means)^2))
  
  # D. Variance Capture (Ratio of Sample SD to Pop SD)
  # Close to 1 means the sample captures the same "width" as the population
  sample_sds <- apply(pts_df, 2, sd)
  var_ratio <- mean(sample_sds / pop_sds)
  
  return(c(
    Area_Covered = round(area, 2), 
    Uniformity = round(avg_dist, 2), 
    Bias_Score = round(rep_score, 4), 
    Variance_Ratio = round(var_ratio, 3)
  ))
}

# 4. Generate and Print descriptive stats table
results <- do.call(rbind, lapply(sample_list, calc_all_metrics, pop_means, pop_sds))
results_table <- data.frame(Method = rownames(results), results)

print("--- Feature Space Comparison Table ---");print(results_table[-1])

#Area (Convex Hull): Shows how much of the "extreme" feature space each method captured. cLHS usually wins here because its algorithm specifically hunts for the edges of the distribution.

#Avg_Spacing: Measures how spread out the points are. A higher number means the points are more dispersed (common in Centroid sampling), while a lower number indicates points are closer together (common in Stratified if a cluster is small).

# Optional: Visualize as a clean table in RStudio
# View(summary_table)

#What do these new metrics mean? 

#Area_Covered: Look for the highest number to see which method captured the most "environmental space." (Usually cLHS).

#Bias_Score: A higher number here means the sample is further from the population average (less representative of the "typical" pixel).
#Bias Score (Representativeness): This is the distance between the "center of gravity" of your sample and the "center of gravity" of the whole map.

# Ideally with large enough samples - FSCS-Stratified usually has the best (lowest) score because it samples proportional to density.cLHS might have a higher bias because it forces samples into the "tails" (extremes).

#Uniformity: Higher bars mean the points are more evenly spread out from each other (Usually FSCS-Centroid).

#Variance_Ratio: This shows which method is "boldest" in capturing the full width of the data distribution.
#Variance Ratio: This tells you if your sample is too "clumped" or "extreme."A ratio of 1.0 is a perfect match.> 1.0 means your sample is over-representing the extremes (typical of cLHS).< 1.0 means your sample is too conservative and staying too close to the average.

#Pro-Tip: The "Winner"There is no single "winner," but this table helps you justify your choice:Use cLHS if Area_Covered and Variance_Ratio are your priorities (best for mapping rare soils).Use FSCS-Centroid if Uniformity is the goal (best for general interpolation).Use FSCS-Stratified if Bias_Score is most important (best for calculating global averages).


## Create shapefiles of sample locations

## Make sure to set working directory to folder is where you want the shapefile to be written
setwd(r"{C:\rwork}")

# write out sampling points
st_write(clhs_pts, "clhs_samp.shp", delete_layer=T)
st_write(cent_pts, "fscs_centroids_samp.shp", delete_layer=T)
st_write(fscs_pts, "fscs_strat_samp.shp", delete_layer=T)

# very useful for finding alternates
writeRaster(k_strat$raster, 'kmeans_samp_stata.tif', overwrite = T)


# Create a map in ArcGIS PRO with you samp_strata.tif and each of the sampling points. Send a screen shot of your final plots and map to your instructor!